#!/bin/bash
apt-get install git-core

apt-get install ruby
apt-get install ruby1.8-dev

apt-get install rubygems

# if gem < 1.3.7
gem install rubygems-update
/var/lib/gems/1.8/bin/update_rubygems 
gem update



# mysql support
apt-get install mysql-server
apt-get install mysql-client
apt-get install libmysqlclient-dev

gem install activerecord
gem install mysql

#driver
gem install serialport

#gtk
apt-get install ruby-gnome2
#gem install gtk2






