#!/bin/bash

case "$1" in
    	start)
        	echo "Starting OpenplacOS"
		su -l openplacos -s /bin/sh -c "/usr/bin/openplacos-server /etc/default/openplacos > /tmp/openplacos.log &"
    if [ $? -gt 0 ]; then
		    exit 1
		else
		    exit 0
		fi
	;;
    	stop)
        	echo "Stopping OpenplacOS"
		pkill openplacos
		if [ $? -gt 0 ]; then
		    exit 1
		else
		    exit 0
		fi
	;;
    	restart)
        	$0 stop
		sleep 1
        	$0 start
        ;;
    	*)
        	echo "usage: $0 {start|stop|restart}"
esac
exit 0
