#!/bin/sh

#
#    This file is part of Openplacos.
#
#    Openplacos is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Openplacos is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Openplacos.  If not, see <http://www.gnu.org/licenses/>.
#

path=`dirname $0`

temp_dir=`mktemp -d`
mkdir -p $temp_dir/openplacos/usr/lib/ruby/
rm /tmp/openplacos.deb
cp -rf $path/../../openplacos $temp_dir/openplacos/usr/lib/ruby/
cp -rf $path/../DEBIAN $temp_dir/openplacos

cd $temp_dir
dpkg-deb --build openplacos

mv openplacos.deb /tmp/