#!/bin/sh

#
#    This file is part of Openplacos.
#
#    Openplacos is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Openplacos is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Openplacos.  If not, see <http://www.gnu.org/licenses/>.
#

path=`dirname $0`
version=$1
temp_dir=`mktemp -d`
dir_version=openplacos_$version

mkdir -p $temp_dir/$dir_version
cp -rf $path/../../openplacos $temp_dir/$dir_version
mv $temp_dir/$dir_version/openplacos/DEBIAN $temp_dir/$dir_version/debian
mv $temp_dir/$dir_version/openplacos/Makefile $temp_dir/$dir_version/Makefile

rm -rf $temp_dir/$dir_version/openplacos/.git

cd $temp_dir/$dir_version

debuild -S -sa

pwd
