#!/bin/bash

path=`dirname $0`

# Fonction: installation
installation() {
  # Pre-requis
    echo "----------------------------------------------------"
    echo "Dependencies installation"
    echo "----------------------------------------------------"
    gem install rubygems-update
  /var/lib/gems/1.8/bin/update_rubygems 
  gem update
  echo "----------------------------------------------------"
  echo "Ruby gem lib installation "
  echo "This could take about 10 min -- please wait"
  echo "----------------------------------------------------"
  gem install --no-ri --no-rdoc activerecord mysql serialport 

  # User openplacos
  echo "----------------------------------------------------"
  echo "User OpenplacOS"
  echo "----------------------------------------------------"
  adduser openplacos --system -disabled-login -no-create-home
  echo "openplacos user added"

   # Files copies
  echo "----------------------------------------------------"
  echo "File copy in your system"
  echo "----------------------------------------------------"
##  cp -rf $path/../openplacos/ /usr/lib/ruby/

# link into path
  ln -s /usr/lib/ruby/openplacos/server/Top.rb /usr/bin/openplacos-server
  ln -s /usr/lib/ruby/openplacos/client/CLI_client/opos-client.rb /usr/bin/openplacos
  ln -s /usr/lib/ruby/openplacos/client/IHMlocal/IHM.rb /usr/bin/openplacos-gtk

# default config
  cp  /usr/lib/ruby/openplacos/server/config_with_VirtualPlacos.yaml /etc/default/openplacos

# dbus integration
  cp  /usr/lib/ruby/openplacos/setup_files/*.service /usr/share/dbus-1/system-services/
  cp  /usr/lib/ruby/openplacos/setup_files/openplacos.conf /etc/dbus-1/system.d/

# Start with system
  cp /usr/lib/ruby/openplacos/setup_files/openplacos /etc/init.d/
  update-rc.d openplacos defaults 98 02

}

installation
