#!/bin/bash

path=`dirname $0`

# Fonction: installation
installation() {

  # Pre-requis
  echo "----------------------------------------------------"
  echo "Ruby gem lib installation "
  echo "This could take about 10 min -- please wait"
  echo "----------------------------------------------------"
  gem install activerecord mysql serialport openplacos micro-optparse choice rails --bindir /usr/bin --no-ri --no-rdoc
   
  # User openplacos
    adduser openplacos --system -disabled-login -no-create-home
    adduser openplacos dialout

  # default config
  if [ -e /etc/default/openplacos ]
  then
    echo "config file already exist"
  else  
    cp /usr/lib/ruby/openplacos/server/config_with_VirtualPlacos.yaml /etc/default/openplacos
  fi 

  # link into path
    ln -s -f /usr/lib/ruby/openplacos/server/main.rb /usr/bin/openplacos-server
    ln -s -f /usr/lib/ruby/openplacos/clients/CLI_client/opos-client.rb /usr/bin/openplacos
    ln -s -f /usr/lib/ruby/openplacos/clients/xml-rpc/xml-rpc-client.rb  /usr/bin/openplacos-xmlrpc
    ln -s -f /usr/lib/ruby/openplacos/clients/soap/soap-client.rb  /usr/bin/openplacos-soap


  # reload dbus
    /etc/init.d/dbus reload

  # Start with system
    update-rc.d openplacos defaults 98 02
    
  # rails bundle install
    
    echo "----------------------------------------------------"
    echo "rails bundle installation "
    echo "This could take about 10 min -- please wait"
    echo "----------------------------------------------------"
    
    cd /usr/lib/ruby/openplacos/plugins/rorplacos/
    bundle install
    
    mkdir tmp
    chown -R openplacos tmp
    chown -R openplacos log
    
    #remove Gemfile.lock
    if [ -e /usr/lib/ruby/openplacos/plugins/rorplacos/Gemfile.lock ]
    then
      rm -f /usr/lib/ruby/openplacos/plugins/rorplacos/Gemfile.lock
    fi 

}

if [ "$1" = "configure" ]; then
    installation
fi
