#!/bin/bash

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then

    # stoping openplacos process (nice and hard way)
    /etc/init.d/openplacos stop
    killall -9 -u openplacos 
    
    update-rc.d openplacos disable
    
    # delete user
    userdel openplacos
    
    # remove dbus configuration file
    rm /etc/dbus-1/system.d/openplacos.conf
    
    #remove openplacos service
    rm /etc/init.d/openplacos
    
fi

if [ "$1" = "purge" ] ; then
    rm /etc/default/openplacos
    rm -rf /usr/lib/ruby/openplacos
fi
