#!/bin/bash


PID=$(cat /tmp/openplacos.pid 2>/dev/null)

case "$1" in
    	start)
        	stat_busy "Starting OpenplacOS"
		[ -z $PID ] && su -l openplacos -s /bin/sh -c "/usr/bin/openplacos-server /etc/default/openplacos &> /tmp/openplacos.log &"
		if [ $? -gt 0 ]; then
			stat_fail
		else
			add_daemon openplacos
			stat_done
		fi
	;;
    	stop)
        	stat_busy "Stopping OpenplacOS"
		[ ! -z $PID ] && kill $PID &> /dev/null
		if [ $? -gt 0 ]; then
			stat_fail
		else
			rm_daemon openplacos
			stat_done
		fi
	;;
    	restart)
        	$0 stop
		sleep 1
        	$0 start
        ;;
    	*)
        	echo "usage: $0 {start|stop|restart}"
esac
exit 0
